import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Dimensions,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { TrendingUp, Users, DollarSign, Target } from 'lucide-react-native';
import { mockAnalytics, mockPromoterStats } from '@/mocks/analytics';

const { width } = Dimensions.get('window');

export default function AnalyticsScreen() {
  const [analytics] = useState(mockAnalytics);
  const [promoters] = useState(mockPromoterStats);

  const maxPeakRevenue = Math.max(...analytics.peakHours.map(h => h.revenue));

  return (
    <SafeAreaView style={styles.container} edges={['bottom']}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Analytics & ROI</Text>
          <Text style={styles.headerDescription}>
            Deep insights into revenue, traffic, and promoter performance
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Peak Hours Analysis</Text>
          <View style={styles.chartContainer}>
            {analytics.peakHours.map((hour, index) => {
              const barHeight = (hour.revenue / maxPeakRevenue) * 120;
              return (
                <View key={index} style={styles.barWrapper}>
                  <View style={styles.barContainer}>
                    <View style={[styles.bar, { height: barHeight }]}>
                      <Text style={styles.barValue}>${(hour.revenue / 1000).toFixed(1)}K</Text>
                    </View>
                  </View>
                  <Text style={styles.hourLabel}>{hour.hour}:00</Text>
                  <Text style={styles.guestLabel}>{hour.guests}</Text>
                </View>
              );
            })}
          </View>
        </View>

        <View style={styles.metricsSection}>
          <Text style={styles.sectionTitle}>Key Metrics</Text>
          <View style={styles.metricsGrid}>
            <View style={styles.metricCard}>
              <View style={styles.metricIcon}>
                <DollarSign size={20} color="#00ff88" />
              </View>
              <Text style={styles.metricLabel}>Total Revenue</Text>
              <Text style={styles.metricValue}>
                ${(analytics.totalRevenue / 1000).toFixed(1)}K
              </Text>
              <Text style={styles.metricSubtext}>
                Avg: ${analytics.averageSpend} per guest
              </Text>
            </View>

            <View style={styles.metricCard}>
              <View style={styles.metricIcon}>
                <Users size={20} color="#00d4ff" />
              </View>
              <Text style={styles.metricLabel}>Unique Guests</Text>
              <Text style={styles.metricValue}>{analytics.uniqueGuests}</Text>
              <Text style={styles.metricSubtext}>
                {analytics.newMembers} new members
              </Text>
            </View>

            <View style={styles.metricCard}>
              <View style={styles.metricIcon}>
                <TrendingUp size={20} color="#ff6b9d" />
              </View>
              <Text style={styles.metricLabel}>Transactions</Text>
              <Text style={styles.metricValue}>{analytics.totalTransactions}</Text>
              <Text style={styles.metricSubtext}>
                {analytics.vipUpgrades} VIP upgrades
              </Text>
            </View>

            <View style={styles.metricCard}>
              <View style={styles.metricIcon}>
                <Target size={20} color="#ffa64d" />
              </View>
              <Text style={styles.metricLabel}>Conversion Rate</Text>
              <Text style={styles.metricValue}>
                {((analytics.vipUpgrades / analytics.uniqueGuests) * 100).toFixed(1)}%
              </Text>
              <Text style={styles.metricSubtext}>
                Guest to VIP
              </Text>
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Promoter Performance</Text>
          <Text style={styles.sectionDescription}>
            Track revenue generated by promoters and calculate their ROI
          </Text>

          {promoters.map(promoter => {
            const roi = (promoter.totalRevenue / promoter.payout).toFixed(1);
            return (
              <View key={promoter.promoterId} style={styles.promoterCard}>
                <View style={styles.promoterHeader}>
                  <View>
                    <Text style={styles.promoterName}>{promoter.promoterName}</Text>
                    <Text style={styles.promoterCode}>{promoter.uniqueTrackingCode}</Text>
                  </View>
                  <View style={styles.roiBadge}>
                    <Text style={styles.roiLabel}>ROI</Text>
                    <Text style={styles.roiValue}>{roi}x</Text>
                  </View>
                </View>

                <View style={styles.promoterStats}>
                  <View style={styles.statItem}>
                    <Text style={styles.statLabel}>Guests Brought</Text>
                    <Text style={styles.statValue}>{promoter.totalGuestsBrought}</Text>
                  </View>
                  <View style={styles.statItem}>
                    <Text style={styles.statLabel}>Revenue</Text>
                    <Text style={styles.statValue}>
                      ${(promoter.totalRevenue / 1000).toFixed(1)}K
                    </Text>
                  </View>
                  <View style={styles.statItem}>
                    <Text style={styles.statLabel}>LTV</Text>
                    <Text style={styles.statValue}>${promoter.lifetimeValue}</Text>
                  </View>
                  <View style={styles.statItem}>
                    <Text style={styles.statLabel}>Conversion</Text>
                    <Text style={styles.statValue}>
                      {(promoter.conversionRate * 100).toFixed(0)}%
                    </Text>
                  </View>
                </View>

                <View style={styles.payoutRow}>
                  <Text style={styles.payoutLabel}>Owed Payout:</Text>
                  <Text style={styles.payoutValue}>${promoter.payout.toLocaleString()}</Text>
                </View>
              </View>
            );
          })}
        </View>

        <View style={styles.bottomPadding} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0f',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800' as const,
    color: '#fff',
    marginBottom: 8,
  },
  headerDescription: {
    fontSize: 14,
    color: '#999',
    lineHeight: 20,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#fff',
    marginBottom: 4,
  },
  sectionDescription: {
    fontSize: 13,
    color: '#999',
    marginBottom: 16,
  },
  chartContainer: {
    flexDirection: 'row' as const,
    alignItems: 'flex-end' as const,
    justifyContent: 'space-between' as const,
    backgroundColor: '#15151f',
    borderRadius: 16,
    padding: 20,
    paddingTop: 40,
    borderWidth: 1,
    borderColor: '#1f1f2e',
    marginTop: 16,
  },
  barWrapper: {
    alignItems: 'center' as const,
    flex: 1,
  },
  barContainer: {
    height: 140,
    justifyContent: 'flex-end' as const,
    marginBottom: 8,
  },
  bar: {
    width: 24,
    backgroundColor: '#00ffcc',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    alignItems: 'center' as const,
    justifyContent: 'flex-start' as const,
    paddingTop: 4,
  },
  barValue: {
    fontSize: 9,
    fontWeight: '700' as const,
    color: '#0a0a0f',
  },
  hourLabel: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: '#fff',
    marginBottom: 2,
  },
  guestLabel: {
    fontSize: 10,
    color: '#666680',
  },
  metricsSection: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  metricsGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 12,
  },
  metricCard: {
    width: (width - 52) / 2,
    backgroundColor: '#15151f',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: '#1f1f2e',
  },
  metricIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(0, 255, 204, 0.1)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginBottom: 12,
  },
  metricLabel: {
    fontSize: 12,
    color: '#999',
    marginBottom: 6,
    fontWeight: '500' as const,
  },
  metricValue: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: '#fff',
    marginBottom: 4,
  },
  metricSubtext: {
    fontSize: 11,
    color: '#666680',
  },
  promoterCard: {
    backgroundColor: '#15151f',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#1f1f2e',
  },
  promoterHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    marginBottom: 16,
  },
  promoterName: {
    fontSize: 17,
    fontWeight: '700' as const,
    color: '#fff',
    marginBottom: 4,
  },
  promoterCode: {
    fontSize: 12,
    color: '#999',
    fontWeight: '500' as const,
  },
  roiBadge: {
    backgroundColor: 'rgba(0, 255, 136, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    alignItems: 'center' as const,
  },
  roiLabel: {
    fontSize: 10,
    color: '#00ff88',
    marginBottom: 2,
    fontWeight: '600' as const,
  },
  roiValue: {
    fontSize: 16,
    fontWeight: '800' as const,
    color: '#00ff88',
  },
  promoterStats: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#1f1f2e',
  },
  statItem: {
    alignItems: 'center' as const,
  },
  statLabel: {
    fontSize: 11,
    color: '#999',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: '#fff',
  },
  payoutRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
  },
  payoutLabel: {
    fontSize: 14,
    color: '#999',
    fontWeight: '500' as const,
  },
  payoutValue: {
    fontSize: 18,
    fontWeight: '800' as const,
    color: '#00ffcc',
  },
  bottomPadding: {
    height: 40,
  },
});
